# Generated by Django 3.2.8 on 2021-10-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_events_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='country',
        ),
    ]
