# Generated by Django 3.2.8 on 2021-10-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_events_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='country',
        ),
    ]
