# Generated by Django 3.2.8 on 2021-10-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_events_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='no_of_members',
        ),
        migrations.AddField(
            model_name='events',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
